server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期(60*60*24*7)
  timeout: 604800
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  isReadHeader: true
  # token前缀
  token-prefix: Bearer
  # jwt秘钥
  jwt-secret-key: sa-secret-key123

# 访问白名单路径
secure:
  ignored:
    urls: #安全路径白名单
      - /
      - /swagger-ui.html
      - /swagger-ui/
      - /*.html
      - /favicon.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /**/*.png
      - /swagger-resources/**
      - /v3/api-docs/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/isLogin

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    com.macro.mall.tiny: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match:
       - '/brand/**'
       - '/admin/**'
      packages-to-scan: com.macro.mall.tiny
  default-flat-param-object: false
